version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  pgdata: